//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWindow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int No { get; set; } = 0;
        public int Id { get; set; }
        public string Content { get; set; }
        public int User_Id { get; set; }
        public int News_Id { get; set; }
        public Comment Clone()
        {
            Comment comment = new Comment()
            {
                 Content=this.Content,
                  Id=this.Id,
                   //News=this.News,
                    News_Id=this.News_Id,
                     No=this.No,
                    //  User=this.User,
                       User_Id=this.User_Id
            };
            return comment;
        }
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
